---
- name: Download {{ get_plugins_repo | basename }}
  tags: plugins
  ansible.builtin.git:
    repo: "{{ get_plugins_repo }}"
    dest: "{{ system.data_location }}/plugins/{{ get_plugins_repo | basename }}"
    single_branch: true
    depth: 1
    version: "{{ get_plugins_branch | default('master') }}"
