alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings '
alias zt='time zsh -i -c exit'
alias ns='netbird status'
alias ka='killall -q'
alias w='curl -s https://wttr.in/London?format=3'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget/history"'
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias txc='perl ~/.local/share/texcount/texcount.pl'
alias tb='toolbox'
alias tbe='toolbox enter'
alias tbr='toolbox run'
alias zke='zk edit -i'
alias tpc='tea pulls c'
alias tm='tea pulls m $1'
