# :vim: set ft=yaml.ansible:
---
- name: Install and configure zsh
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Download core packages
      tags: packages
      become: true
      ansible.builtin.package:
        name:
          - zsh
        state: present

    - name: Download utilities
      tags: packages
      become: true
      block:
        - name: Download fzf
          when: utilities.fzf
          ansible.builtin.package:
            name:
              - fzf
              - ripgrep
              - fd
              - lesspipe
              - bat
              - chafa
            state: present
        - name: Download zoxide
          when: utilities.zoxide
          ansible.builtin.package:
            name:
              - zoxide
            state: present
        - name: Download grc
          when: utilities.grc
          ansible.builtin.package:
            name:
              - grc
            state: present
        - name: Download eza
          when: utilities.eza
          ansible.builtin.package:
            name:
              - eza
            state: present
        - name: Download direnv
          when: utilities.direnv
          ansible.builtin.package:
            name:
              - direnv
            state: present

    - name: Download plugins
      block:
        - name: Get zsh-defer
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/romkatv/zsh-defer
        - name: Get zsh-smartcache
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/QuarticCat/zsh-smartcache
            get_plugins_branch: main
        - name: Get zsh-autosuggestions
          when: plugins.autosuggestions
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/zsh-users/zsh-autosuggestions
        - name: Get zsh-window-title
          when: plugins.window_title
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/olets/zsh-window-title
            get_plugins_branch: main
        - name: Get zsh-autopair
          when: plugins.autopair
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/hlissner/zsh-autopair
        - name: Get zsh-syntax-highlighting
          when: plugins.syntax_highlight
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/zsh-users/zsh-syntax-highlighting
        - name: Get fzf-tab
          when: plugins.fzf_tab
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/Aloxaf/fzf-tab
        - name: Get fzf-tab-source
          when: plugins.fzf_tab
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/Freed-Wu/fzf-tab-source
            get_plugins_branch: main
        - name: Get p10k prompt
          when: plugins.p10k
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/romkatv/powerlevel10k
        - name: Get zsh-vi-mode
          when: plugins.vi_mode
          ansible.builtin.include_role:
            name: get_plugins
          vars:
            get_plugins_repo: https://github.com/jeffreytse/zsh-vi-mode

    - name: Template configuration
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/{{ item }}.j2"
        dest: "{{ playbook_dir }}/{{ item }}"
        mode: "0644"
      with_items:
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

    - name: Make symbolic link to ZDOTDIR
      ansible.builtin.file:
        src: "{{ playbook_dir }}"
        dest: "{{ system.config_location }}"
        state: link

    - name: Make symbolic link to .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: "/home/{{ current_user }}/.zshenv"
        state: link

    - name: Make symbolic link to .lessfilter
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/.lessfilter"
        dest: "/home/{{ current_user }}/.lessfilter"
        state: link
