# :vim: set ft=yaml.ansible:
---
current_user: "{{ lookup('env', 'USER') }}"

# ~~ (0) SYSTEM CONFIGURATION ~~

system:
  data_location: "$XDG_DATA_HOME/zsh" # where to place history and plugins
  config_location: "$XDG_CONFIG_HOME/zsh" # where to place configs
  terminal: "alacritty" # the terminal to use (to set $TERM)
  aur_helper: "yay" # supports paru or yay, change to 'sudo pacman' if not using

# ~~ (1) UTILITIES  ~~

# Other utilities that can be integrated with zsh
# Setting to true will install and configure them

utilities:
  fzf: true # fuzzy file sorter TUI
  zoxide: true # quick cd based on frequency
  grc: true # colorize output
  eza: true # better ls
  direnv: true # env file configuration

# ~~ (2) PLUGINS  ~~

plugins:
  autosuggestions: true # autocomplete inline suggestions
  window_title: true # auto change the window title to match proc
  autopair: true # auto add matching parens
  syntax_highlight: true # zsh syntax highlighting
  command_not_found: true # display package suggestion if command not found
  fzf_tab: true # tab complete with fzf
  p10k: true # prompt for zsh
  vi_mode: true # enable vi-mode

# ~~ (3) ZSHENV ~~

# The .zshenv file is sourced every zsh session.
# Bare minimum variables go here.
# For user applications, use .zprofile in section (4).
# Some 'necessary' ones are included.
# Expects a list.
zshenv_variables:
  - LANG: "en_GB.UTF-8"
  - XDG_CONFIG_HOME: "$HOME/.config"
  - XDG_CACHE_HOME: "$HOME/.cache"
  - XDG_DATA_HOME: "$HOME/.local/share"
  - XDG_STATE_HOME: "$HOME/.local/share"
  - ZDOTDIR: "{{ system.config_location }}"
  - ERR_FILE: "$XDG_CACHE_HOME/X11/xsession-errors"

# ~~ (4) ZPROFILE ~~

# The .zprofile file is sourced for a login session.
# We can set stuff like PATH here
# Expects a list.
zprofile_variables:
  - TRASH: "$XDG_DATA_HOME/Trash/files"
  - _GL_SYNC_DISPLAY_DEVICE: "DP-2"
  - VDPAU_DRIVER: "nvidia"
  - LIBVA_DRIVER_NAME: "vdpau"
  - BROWSER: "/usr/bin/firefox"
  - TERMINAL: "{{ system.terminal }}"
  - MANPAGER: "nvim +Man!"
  - DIFFPROG: "nvim"
  - EDITOR: "/usr/bin/nvim"
  - PAGER: "nvim -R"
  - GTK_IM_MODULE: "fcitx"
  - QT_IM_MODULE: "fcitx"
  - XMODIFIERS: "@im=fcitx"
  - QT4_IM_MODULE: "fcitx"
  - CLUTTER_IM_MODULE: "fcitx"
  - GLFW_IM_MODULE: "fcitx"
  - W3M_DIR: "$XDG_STATE_HOME/w3m"
  - RUSTUP_HOME: "$XDG_DATA_HOME/rustup"
  - BUNDLE_USER_CONFIG: "$XDG_CONFIG_HOME/bundle"
  - BUNDLE_USER_CACHE: "$XDG_CACHE_HOME/bundle"
  - BUNDLE_USER_PLUGIN: "$XDG_DATA_HOME/bundle"
  - _JAVA_OPTIONS: "-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
  - _JAVA_OPTIONS: "-Djavafx.cachedir=$XDG_CACHE_HOME/openjfx"
  - CONAN_USER_HOME: "$XDG_CONFIG_HOME/conan"
  - ANDROID_HOME: "$XDG_DATA_HOME/android"
  - MYSQL_HISTFILE: "$XDG_DATA_HOME/mysql/mysql_history"
  - PYTHONSTARTUP: "/etc/python/pythonrc"
  - GOPATH: "$XDG_DATA_HOME/go"
  - CUDA_CACHE_PATH: "$XDG_CACHE_HOME/nv"
  - GTK2_RC_FILES: "$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
  - CARGO_HOME: "$XDG_DATA_HOME/cargo"
  - NUGET_PACKAGES: "$XDG_CACHE_HOME/NuGetPackages"
  - JUPYTER_CONFIG_DIR: "$XDG_CONFIG_HOME/jupyter"
  - STACK_ROOT: "$XDG_DATA_HOME/stack"
  - IPYTHONDIR: "$XDG_CONFIG_HOME/jupyter"
  - LESSKEY: "$XDG_CONFIG_HOME/less/lesskey"
  - LESSHISTFILE: "$XDG_CACHE_HOME/less/history"
  - WEECHAT_HOME: "$XDG_CONFIG_HOME/weechat"
  - WINEPREFIX: "$XDG_DATA_HOME/wineprefixes/default"
  - GRADLE_USER_HOME: "$XDG_DATA_HOME/gradle"
  - NPM_CONFIG_USERCONFIG: "$XDG_CONFIG_HOME/npm/npmrc"
  - BAT_CONFIG_PATH: "$XDG_CONFIG_HOME/bat/config"
  - ANSIBLE_GALAXY_CACHE_DIR: "$XDG_CACHE_HOME/ansible/galaxy_cache"
  - ANSIBLE_HOME: "$XDG_CONFIG_HOME/ansible"
  - XCURSOR_PATH: "/usr/share/icons:$XDG_DATA_HOME/icons"
  - MYPY_CACHE_DIR: "$XDG_CACHE_HOME/mypy"
  - KERAS_HOME: "$XDG_STATE_HOME/keras"
  - TEXMFVAR: "$XDG_CACHE_HOME/texlive/texmf-var"
  - LUA_PATH: "/usr/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?.lua;\
      /usr/local/share/lua/5.4/?/init.lua;/usr/share/lua/5.4/?/init.lua;\
      /usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;\
      /usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;\
      /$HOME/.luarocks/share/lua/5.1/?.lua;\
      /$HOME/.luarocks/share/lua/5.1/?/init.lua"
  - ANSIBLE_VENV: "$HOME/projects/.ansible_venv"
  - NODE_PATH: "$HOME/.local/share/nvim/mason/packages/commitlint/node_modules"

# Configure directories to append to PATH here
path:
  - "$HOME/.local/share/applications"
  - "$HOME/.local/bin"
  - "$HOME/scripts/bin"
  - "$HOME/.local/share/cargo/bin"
  - "$HOME/.local/share/go/bin"

# ~~ (5) FZF THEMING ~~

# Make it look like nvim's telescope
# Extra colors for FZF
# The background color is set to grey (8)
# Adjust accordingly
fzf:
  foreground: "#574b42"
  preview_bg: "#ded8d3"
  selected_bg: "#bdb1a8"
